### ISSUE TITLE
Histogram display

### ISSUE THREAD

**Issue by enoch-chang** [enoch-chang/ImageProcessorS18#23]
I see that in your code you do the plotting within your code but I thought we were plotting the histogram on the front-end using ```recharts```? Right now I have code written to take in simply three arrays (one for each color channel) of 2 lists (x and y values for the plot). I dont think I can take your histogram plots the way you have them presented right now for display. Or am I missing something here?

**Comment by an-schneider** [comment]
Good catch. I will update my code today

**Comment by an-schneider** [comment]
Fixed this by adding a function named "output_histogram_data"
